version: '3.8'

services:
  # Redis for queue management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Main API application
  api:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data
      - ./financial_analyzer.db:/app/financial_analyzer.db
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  # Background worker
  worker:
    build: .
    command: python start_worker.py
    volumes:
      - ./data:/app/data
      - ./financial_analyzer.db:/app/financial_analyzer.db
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: